// This file was generated by splitting combat-related logic out of Mobile.cs
// It intentionally contains only combat-related classes, delegates, timers and methods.
// Note: To avoid duplicate symbol definitions during compilation, this file places the members
// inside a partial class and does not redefine types already defined elsewhere in Mobile.cs.

using Server.Network;
using System;
using System.Collections.Generic;

namespace Server
{
    public partial class Mobile
    {
        // Combat fields
        private CombatGroup m_CombatGroup;
        private List<AggressorInfo> m_Aggressors = new List<AggressorInfo>();
        private List<AggressorInfo> m_Aggressed = new List<AggressorInfo>();
        private CombatTimer m_CombatTimer;
        private ExpireCombatantTimer m_ExpireCombatant;
        private long m_NextCombatTime;
        private IDamageable m_Combatant;
        private int m_ChangingCombatant;

        // Initialization hook for cleanup on delete/disconnection
        private static readonly bool s_CombatCleanupHooks = InitCombatCleanupHooks();

        public List<AggressorInfo> Aggressors => m_Aggressors;
        public List<AggressorInfo> Aggressed => m_Aggressed;

        public long NextCombatTime
        {
            get => m_NextCombatTime;
            set => m_NextCombatTime = value;
        }

        // CombatGroup property (may be null)
        public CombatGroup Group => m_CombatGroup;

        // Hook di inizializzazione per cleanup su delete/disconnessione
        private static bool InitCombatCleanupHooks()
        {
            EventSink.MobileDeleted += e => CleanupCombatGroup(e.Mobile);
            EventSink.Logout += e => CleanupCombatGroup(e.Mobile);
            return true;
        }

        private static void CleanupCombatGroup(Mobile mobile)
        {
            if (mobile == null)
            {
                return;
            }

            CombatGroup group = mobile.m_CombatGroup;

            if (group != null)
            {
                group.RemoveCombatant(mobile);
                mobile.m_CombatGroup = null;

                // Clean invalid members and recompute components if necessary
                if (group.ValidateGroupIntegrity())
                {
                    CombatGroup.RecalculateCombatGroups(group);
                }
            }
        }

        /// <summary>
        /// CombatGroup: encapsulates membership and connectivity based on aggression.
        /// Public surface minimal: external code can enumerate via ForEachCombatant only.
        /// Internal APIs provide efficient mutation for Mobile internals.
        /// Assumes single-threaded execution.
        /// </summary>
        public sealed class CombatGroup
        {
            private readonly List<Mobile> m_Combatants;
            // Maintain a HashSet mirror for O(1) membership checks. Keeps in sync with m_Combatants.
            private readonly HashSet<Mobile> m_CombatantSet;
            // Hue for visual feedback of group members
            private int m_GroupHue;

            // Constants for hue generation
            private static readonly int MinGroupHue = 1;
            private static readonly int MaxGroupHue = 1000;

            public CombatGroup()
            {
                m_Combatants = new List<Mobile>();
                m_CombatantSet = new HashSet<Mobile>();
                m_GroupHue = Utility.Random(MinGroupHue, MaxGroupHue);
            }

            // Public safe enumerator. External code should use this for read-only operations.
            /// <summary>
            /// Executes the specified action on each combatant in the group, using a snapshot to allow safe modifications during enumeration.
            /// </summary>
            /// <param name="action">The action to perform on each mobile.</param>
            public void ForEachCombatant(Action<Mobile> action)
            {
                if (action == null)
                {
                    return;
                }

                // Use snapshot to allow safe modifications during enumeration.
                Mobile[] snapshot = m_Combatants.ToArray();

                for (int i = 0; i < snapshot.Length; i++)
                {
                    action(snapshot[i]);
                }
            }

            // Internal: add/remove/count/validate are for Mobile internals only.
            internal void AddCombatant(Mobile mobile)
            {
                if (mobile == null || mobile.Deleted)
                {
                    return;
                }

                CombatGroup old = mobile.m_CombatGroup;

                if (old != null && old != this)
                {
                    old.RemoveCombatant(mobile);
                }

                if (m_CombatantSet.Add(mobile))
                {
                    m_Combatants.Add(mobile);
                }

                if (mobile.m_CombatGroup != this)
                {
                    mobile.m_CombatGroup = this;
                }

                mobile.SolidHueOverride = m_GroupHue;
            }

            internal void RemoveCombatant(Mobile mobile)
            {
                if (mobile == null)
                {
                    return;
                }

                if (m_CombatantSet.Remove(mobile))
                {
                    // Remove from list (O(n)) - acceptable for expected small group sizes.
                    m_Combatants.Remove(mobile);
                }

                if (mobile.m_CombatGroup == this)
                {
                    mobile.m_CombatGroup = null;
                }

                // Reset visual feedback
                mobile.SolidHueOverride = -1;
            }

            internal int Count => m_CombatantSet.Count;

            internal bool ValidateGroupIntegrity()
            {
                HashSet<Mobile> seen = new HashSet<Mobile>();

                for (int i = m_Combatants.Count - 1; i >= 0; --i)
                {
                    Mobile m = m_Combatants[i];

                    if (m == null || m.Deleted || m.m_CombatGroup != this || !seen.Add(m))
                    {
                        m_Combatants.RemoveAt(i);
                        // Reset group reference and visual feedback for removed member
                        m.m_CombatGroup = null;
                        m.SolidHueOverride = -1;
                    }
                }

                // Rebuild member set to match list after cleanup
                m_CombatantSet.Clear();
                for (int i = 0; i < m_Combatants.Count; ++i)
                {
                    Mobile m2 = m_Combatants[i];
                    if (m2 != null)
                    {
                        m_CombatantSet.Add(m2);
                    }
                }

                return m_Combatants.Count > 0;
            }

            internal CombatGroup MergeWith(CombatGroup other)
            {
                if (other == null || other == this)
                {
                    return this;
                }

                ValidateGroupIntegrity();
                other.ValidateGroupIntegrity();

                HashSet<Mobile> existing = new HashSet<Mobile>(m_CombatantSet);

                for (int i = 0; i < other.m_Combatants.Count; i++)
                {
                    Mobile m = other.m_Combatants[i];

                    if (m != null && !m.Deleted && existing.Add(m))
                    {
                        m_Combatants.Add(m);
                        m_CombatantSet.Add(m);
                        m.m_CombatGroup = this;
                        // Update visual feedback to match this group's hue
                        m.SolidHueOverride = m_GroupHue;
                    }
                }

                // Clear source
                other.m_Combatants.Clear();
                other.m_CombatantSet.Clear();

                return this;
            }

            internal void SetCombatants(IEnumerable<Mobile> members)
            {
                // Clear backrefs
                for (int i = 0; i < m_Combatants.Count; i++)
                {
                    Mobile old = m_Combatants[i];

                    if (old != null && !old.Deleted && old.m_CombatGroup == this)
                    {
                        old.m_CombatGroup = null;
                    }
                }

                m_Combatants.Clear();
                m_CombatantSet.Clear();

                if (members == null)
                {
                    return;
                }

                foreach (Mobile m in members)
                {
                    if (m == null || m.Deleted)
                    {
                        continue;
                    }

                    CombatGroup old = m.m_CombatGroup;

                    if (old != null && old != this)
                    {
                        // Remove the member immediately from the old group's set and list to
                        // preserve immediate consistency. This is O(n) on the old list but
                        // guarantees that no stale entries remain during subsequent operations.
                        old.m_CombatantSet.Remove(m);
                        old.m_Combatants.Remove(m);

                        // Validate to ensure the old group's internal state is consistent.
                        old.ValidateGroupIntegrity();
                    }

                    if (m_CombatantSet.Add(m))
                    {
                        m_Combatants.Add(m);
                    }

                    if (m.m_CombatGroup != this)
                    {
                        m.m_CombatGroup = this;
                        // Set visual feedback for the new group
                        m.SolidHueOverride = m_GroupHue;
                    }
                }
            }

            // Internal: compute components using BFS over aggression graph.
            // Note: component discovery is performed inline inside SplitIntoCombatSubgroups
            // to avoid allocating an intermediate List<List<Mobile>> when the caller only
            // needs to assign the components immediately.
            internal void SplitIntoCombatSubgroups()
            {
                if (!ValidateGroupIntegrity() || Count <= 1)
                {
                    return;
                }

                Mobile[] snapshot = m_Combatants.ToArray();
                HashSet<Mobile> remaining = new HashSet<Mobile>(snapshot);

                bool firstAssigned = false;

                while (remaining.Count > 0)
                {
                    Mobile seed = null;

                    foreach (Mobile candidate in remaining)
                    {
                        seed = candidate;
                        break;
                    }

                    if (seed == null)
                    {
                        break;
                    }

                    List<Mobile> component = new List<Mobile>();
                    Queue<Mobile> queue = new Queue<Mobile>(remaining.Count);

                    queue.Enqueue(seed);
                    remaining.Remove(seed);

                    while (queue.Count > 0)
                    {
                        Mobile current = queue.Dequeue();

                        if (current == null || current.Deleted)
                        {
                            continue;
                        }

                        component.Add(current);

                        // Enqueue neighbors directly without creating a temporary list
                        EnqueueAggressionLinks(current, remaining, queue);
                    }

                    if (!firstAssigned)
                    {
                        // Assign first component to this group
                        SetCombatants(component);
                        firstAssigned = true;
                    }
                    else
                    {
                        CombatGroup newGroup = new CombatGroup();
                        newGroup.SetCombatants(component);
                    }
                }
            }

            // Enqueues neighbors (aggressors and aggressed defenders) that are present in 'remaining'
            // directly into the BFS queue; avoids allocating temporary neighbor lists.
            private void EnqueueAggressionLinks(Mobile mobile, HashSet<Mobile> remaining, Queue<Mobile> queue)
            {
                List<AggressorInfo> aggressors = mobile.m_Aggressors;

                if (aggressors != null)
                {
                    for (int i = 0; i < aggressors.Count; ++i)
                    {
                        Mobile attacker = aggressors[i].Attacker;
                        if (attacker != null && remaining.Remove(attacker))
                        {
                            queue.Enqueue(attacker);
                        }
                    }
                }

                List<AggressorInfo> aggressed = mobile.m_Aggressed;

                if (aggressed != null)
                {
                    for (int i = 0; i < aggressed.Count; ++i)
                    {
                        Mobile defender = aggressed[i].Defender;
                        if (defender != null && remaining.Remove(defender))
                        {
                            queue.Enqueue(defender);
                        }
                    }
                }
            }

            internal void AssignCombatants(IEnumerable<Mobile> members)
            {
                SetCombatants(members);
            }

            // SplitIntoCombatSubgroups implemented above (inline BFS).
            // The older implementation that built an intermediate List<List<Mobile>> was removed
            // to avoid unnecessary allocations. This placeholder remains for readability.
            internal static void MergeCombatGroups(CombatGroup group1, CombatGroup group2)
            {
                if (group1 != null && !group1.ValidateGroupIntegrity())
                {
                    group1 = null;
                }

                if (group2 != null && !group2.ValidateGroupIntegrity())
                {
                    group2 = null;
                }

                if (group1 == null || group2 == null)
                {
                    return;
                }

                CombatGroup target = group1.Count >= group2.Count ? group1 : group2;
                CombatGroup source = ReferenceEquals(target, group1) ? group2 : group1;

                target.MergeWith(source);

                target.SplitIntoCombatSubgroups();
            }

            internal static void RecalculateCombatGroups(CombatGroup group)
            {
                if (group == null)
                {
                    return;
                }

                group.SplitIntoCombatSubgroups();
            }
        }

        // Mobile logic unchanged below (Combatant, timers, aggressive actions, etc.)

        public virtual IDamageable Combatant
        {
            get => m_Combatant;
            set
            {
                if (m_Deleted)
                {
                    return;
                }

                if (m_Combatant != value && value != this)
                {
                    IDamageable old = m_Combatant;

                    ++m_ChangingCombatant;
                    m_Combatant = value;

                    if (!Region.OnCombatantChange(this, old, m_Combatant) || (m_Combatant != null && !CanBeHarmful(m_Combatant, false)))
                    {
                        m_Combatant = old;
                        --m_ChangingCombatant;
                        return;
                    }

                    if (m_NetState != null)
                    {
                        m_NetState.Send(new ChangeCombatant(m_Combatant));
                    }

                    if (m_Combatant == null)
                    {
                        m_ExpireCombatant?.Stop();
                        m_CombatTimer?.Stop();

                        m_ExpireCombatant = null;
                        m_CombatTimer = null;
                    }
                    else
                    {
                        if (m_ExpireCombatant == null)
                        {
                            m_ExpireCombatant = new ExpireCombatantTimer(this);
                        }

                        m_ExpireCombatant.Start();

                        if (m_CombatTimer == null)
                        {
                            m_CombatTimer = new CombatTimer(this);
                        }

                        m_CombatTimer.Start();
                    }

                    if (m_Combatant != null && CanBeHarmful(m_Combatant, false))
                    {
                        DoHarmful(m_Combatant);

                        if (m_Combatant is Mobile mob)
                        {
                            mob.PlaySound(mob.GetAngerSound());
                        }
                    }

                    OnCombatantChange();
                    --m_ChangingCombatant;
                }
            }
        }

        public bool ChangingCombatant => m_ChangingCombatant > 0;

        public virtual void Attack(IDamageable e)
        {
            if (CheckAttack(e))
            {
                if (!m_Warmode)
                {
                    Warmode = true;
                }

                Combatant = e;
            }
        }

        public virtual bool CheckAttack(IDamageable e)
        {
            return Utility.InUpdateRange(this, e.Location) && CanSee(e) && InLOS(e);
        }

        public virtual void AggressiveAction(Mobile aggressor)
        {
            AggressiveAction(aggressor, false);
        }

        public virtual void AggressiveAction(Mobile aggressor, bool criminal)
        {
            if (aggressor == this)
            {
                return;
            }

            AggressiveActionEventArgs args = AggressiveActionEventArgs.Create(this, aggressor, criminal);
            EventSink.InvokeAggressiveAction(args);
            args.Free();

            if (Combatant == aggressor)
            {
                if (m_ExpireCombatant == null)
                {
                    m_ExpireCombatant = new ExpireCombatantTimer(this);
                }
                else
                {
                    m_ExpireCombatant.Stop();
                }

                m_ExpireCombatant.Start();
            }

            bool addAggressor = true;

            List<AggressorInfo> list = m_Aggressors;
            for (int i = 0; i < list.Count; ++i)
            {
                AggressorInfo info = list[i];

                if (info.Attacker == aggressor)
                {
                    info.Refresh();
                    info.CriminalAggression = criminal;
                    info.CanReportMurder = criminal;

                    addAggressor = false;
                }
            }

            list = aggressor.m_Aggressors;
            for (int i = 0; i < list.Count; ++i)
            {
                AggressorInfo info = list[i];

                if (info.Attacker == this)
                {
                    info.Refresh();

                    addAggressor = false;
                }
            }

            bool addAggressed = true;

            list = m_Aggressed;
            for (int i = 0; i < list.Count; ++i)
            {
                AggressorInfo info = list[i];

                if (info.Defender == aggressor)
                {
                    info.Refresh();

                    addAggressed = false;
                }
            }

            list = aggressor.m_Aggressed;
            for (int i = 0; i < list.Count; ++i)
            {
                AggressorInfo info = list[i];

                if (info.Defender == this)
                {
                    info.Refresh();
                    info.CriminalAggression = criminal;
                    info.CanReportMurder = criminal;

                    addAggressed = false;
                }
            }

            bool setCombatant = false;

            if (addAggressor)
            {
                // Instance for the “attacker -> this” side
                AggressorInfo ai = AggressorInfo.Create(aggressor, this, criminal);
                m_Aggressors.Add(ai);

                if (CanSee(aggressor) && m_NetState != null)
                {
                    m_NetState.Send(MobileIncoming.Create(m_NetState, this, aggressor));
                }

                if (Combatant == null)
                {
                    setCombatant = true;
                }

                UpdateAggrExpire();
            }

            if (addAggressed)
            {
                // Separate instance for the “this <- attacker” side
                AggressorInfo ai = AggressorInfo.Create(aggressor, this, criminal);
                aggressor.m_Aggressed.Add(ai);

                if (CanSee(aggressor) && m_NetState != null)
                {
                    m_NetState.Send(MobileIncoming.Create(m_NetState, this, aggressor));
                }

                if (Combatant == null)
                {
                    setCombatant = true;
                }

                UpdateAggrExpire();
            }

            // Manage BattleGroup relationships based on aggression
            if (addAggressor || addAggressed)
            {
                EnsureCombatGroupWith(aggressor);
            }

            if (setCombatant && !Hidden)
            {
                Combatant = aggressor;
            }

            Region.OnAggressed(aggressor, this, criminal);
        }

        public void RemoveAggressed(Mobile aggressed)
        {
            if (m_Deleted)
            {
                return;
            }

            List<AggressorInfo> list = m_Aggressed;

            for (int i = 0; i < list.Count; ++i)
            {
                AggressorInfo info = list[i];

                if (info.Defender == aggressed)
                {
                    m_Aggressed.RemoveAt(i);
                    info.Free();

                    if (m_NetState != null && CanSee(aggressed))
                    {
                        m_NetState.Send(MobileIncoming.Create(m_NetState, this, aggressed));
                    }

                    break;
                }
            }

            UpdateAggrExpire();
            CheckCombatGroupIntegrity();
        }

        public void RemoveAggressor(Mobile aggressor)
        {
            if (m_Deleted)
            {
                return;
            }

            List<AggressorInfo> list = m_Aggressors;

            for (int i = 0; i < list.Count; ++i)
            {
                AggressorInfo info = list[i];

                if (info.Attacker == aggressor)
                {
                    m_Aggressors.RemoveAt(i);
                    info.Free();

                    if (m_NetState != null && CanSee(aggressor))
                    {
                        m_NetState.Send(MobileIncoming.Create(m_NetState, this, aggressor));
                    }

                    break;
                }
            }

            UpdateAggrExpire();
            CheckCombatGroupIntegrity();
        }

        /// <summary>
        /// Checks the integrity of the CombatGroup and cleans it if necessary.
        /// If the mobile no longer has aggression links, it is removed from the CombatGroup.
        /// If the CombatGroup has fragmented, it is recomputed.
        /// </summary>
        private void CheckCombatGroupIntegrity()
        {
            if (m_CombatGroup == null)
            {
                return;
            }

            // Rimuove membri non validi e, se il gruppo resta vuoto, annulla il riferimento
            if (!m_CombatGroup.ValidateGroupIntegrity())
            {
                m_CombatGroup = null;
                return;
            }

            if (m_Aggressors.Count > 0 || m_Aggressed.Count > 0)
            {
                CombatGroup.RecalculateCombatGroups(m_CombatGroup);
                return;
            }

            m_CombatGroup.RemoveCombatant(this);
            m_CombatGroup = null;
        }

        /// <summary>
        /// Ensures that two mobiles are in the same CombatGroup, creating a new one or merging existing ones.
        /// </summary>
        private void EnsureCombatGroupWith(Mobile other)
        {
            if (other == null || other == this)
            {
                return;
            }

            CombatGroup g1 = m_CombatGroup;
            CombatGroup g2 = other.m_CombatGroup;

            if (g1 != null && !g1.ValidateGroupIntegrity())
            {
                g1 = null;
                m_CombatGroup = null;
            }

            if (g2 != null && !g2.ValidateGroupIntegrity())
            {
                g2 = null;
                other.m_CombatGroup = null;
            }

            if (g1 == null && g2 == null)
            {
                CombatGroup newGroup = new CombatGroup();
                newGroup.AddCombatant(this);
                newGroup.AddCombatant(other);

                m_CombatGroup = newGroup;
                other.m_CombatGroup = newGroup;
                return;
            }

            if (g1 == null && g2 != null)
            {
                g2.AddCombatant(this);
                m_CombatGroup = g2;
                return;
            }

            if (g1 != null && g2 == null)
            {
                g1.AddCombatant(other);
                other.m_CombatGroup = g1;
                return;
            }

            if (g1 != null && g2 != null && !ReferenceEquals(g1, g2))
            {
                CombatGroup.MergeCombatGroups(g1, g2);
            }
        }

        private class CombatTimer : Timer
        {
            private readonly Mobile m_Mobile;

            public CombatTimer(Mobile m)
                : base(TimeSpan.FromSeconds(0.0), TimeSpan.FromSeconds(0.01), 0)
            {
                m_Mobile = m;

                if (!m_Mobile.m_Player && m_Mobile.m_Dex <= 100)
                {
                    Priority = TimerPriority.FiftyMS;
                }
            }

            protected override void OnTick()
            {
                if (Core.TickCount - m_Mobile.m_NextCombatTime >= 0)
                {
                    IDamageable combatant = m_Mobile.Combatant;

                    if (combatant == null || combatant.Deleted || m_Mobile.m_Deleted || combatant.Map != m_Mobile.m_Map ||
                        !combatant.Alive || !m_Mobile.Alive || !m_Mobile.CanSee(combatant) ||
                        (combatant is Mobile && ((Mobile)combatant).IsDeadBondedPet) ||
                        m_Mobile.IsDeadBondedPet)
                    {
                        m_Mobile.Combatant = null;
                        return;
                    }

                    IWeapon weapon = m_Mobile.Weapon;

                    if (!m_Mobile.InRange(combatant, weapon.MaxRange))
                    {
                        return;
                    }

                    if (m_Mobile.InLOS(combatant))
                    {
                        weapon.OnBeforeSwing(m_Mobile, combatant);
                        m_Mobile.RevealingAction();
                        m_Mobile.m_NextCombatTime = Core.TickCount + (int)weapon.OnSwing(m_Mobile, combatant).TotalMilliseconds;
                    }
                }
            }
        }

        private class ExpireCombatantTimer : Timer
        {
            private readonly Mobile m_Mobile;

            public ExpireCombatantTimer(Mobile m)
                : base(TimeSpan.FromMinutes(1.0))
            {
                Priority = TimerPriority.FiveSeconds;
                m_Mobile = m;
            }

            protected override void OnTick()
            {
                m_Mobile.Combatant = null;
            }
        }

        public virtual void OnCombatantChange()
        { }
    }
}
